[package]
name = "animessage"
version = "0.19.6"
authors = ["LeSplooch <34457355+LeSplooch@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.25"
anyhow = "1.0.47"
thiserror = "1.0.30"
simple_logger = "1.13.0"
log = "0.4.14"
rodio = "0.14.0"
crossterm = "0.22.1"
# rdev = "0.4.5"
parking_lot = "0.11.2"
lazy_static = "1.4.0"
console_engine = "2.2.0"
device_query = "0.2.8"
webbrowser = "0.5.5"
read_input = "0.8.6"
asciify = "0.1.6"
image = "0.23.14"
ctrlc = { version = "3.2.1", features = ["termination"] }
smallvec = "1.7.0"
envmnt = "0.9.1"
term-table = "1.3.2"
inquire = "0.2.1"
